### ISSUE TITLE
Will it be ESP32 compatible in future?

### ISSUE THREAD

**Issue by happytm** [hsaturn/TinyMqtt#2]
Nice job. Are you planning to make it compatible with ESP32 in future?

Thanks.

**Comment by hsaturn** [comment]
Thanks
I will receive a Wroom soon, I may try to adapt this lib to the Esp32 only if this is easy. My main goal was the Esp8266 (and 8285).
But before that I have still some work to do, (port this lib to async tcp is what I'm working on today)
