### ISSUE TITLE
Bridged connection from mosquitto broker sets protocol version to 0x84, cannot connect to TinyMqtt

### ISSUE THREAD

**Issue by mkjanke** [hsaturn/TinyMqtt#27]
Seems as though the mosquitto broker will set protocol version in the connect header to 0x84, rather than 0x04 for 3.1.1 connections. They use the 0x80 to identify a bridged connection.

I.E.:

```
*************** Error msg 0x10-------ERROR ------ size(100), state=4
-------ERROR ------ | 10 62 00 04 4D 51 54 54  | .b.. - MQTT |
-------ERROR ------ | 84 2C 00 0A 00 1A 63 61  | �,.. - ..ca |

```
To be able to accept a connection to the TinyMqtt broker from a mosquitto bridge, one needs to mask header[6] before testing:

```
if ( (header[6]&0x7F) != 0x04 )
{
	debug("unknown level");
	break;	// Level 3.1.1
}
```
I cannot locate their use of the spare protocol bits in the MQTT specification. Perhaps they are ahead of the spec.

**Comment by hsaturn** [comment]
0x84 is clearly unacceptable as protocol version. It seems that this is related to mosquito private things.
See here https://stackoverflow.com/questions/59046965/mosquitto-broker-bridge-configuration-unacceptable-protocol-version.
