### ISSUE TITLE
QoS level greater than 0

### ISSUE THREAD

**Issue by FraOre** [hsaturn/TinyMqtt#28]
Hello and thanks for this library.
I would like to ask if there is any possibility to implement a greater QoS than 0?
Thank you,
Francesco

**Comment by hsaturn** [comment]
Hello, sorry for the late answer (personal problems).

TinyMqtt is intented to be used on light devices.
There is no queueing of messages made by the tiny broker (memory does not really allows this, and latency would increase a looot).
So any incoming message is sent immediately to clients.
QoS means that messages are queued and that some garanty are made, but as the messages are forwarded immediately, there is no need for this in tiny broker.

About 1000 to 2000 messages per second can be sent by a single ESP tiny broker.

So except if I really need a QoS greater than 0, I don't plan at all to implement this.

Best regards.
