### ISSUE TITLE
How to see message arriving at MQTT broker

### ISSUE THREAD

**Issue by shivaniumredkar1102** [hsaturn/TinyMqtt#29]
Dear friends, 

We are establishing local MQTT communication on esp32 with the help of this library. Basically the message is visible on end node. But it is not visible on local broker. Any help on it, It will be appreciable. 

Thanks.

**Comment by hsaturn** [comment]
You can try 
#define TINY_MQTT_DEBUG
just before
#include <TinyMqtt.h>

Unfortunately, I've tried this and this leads to a compilation error (0.9.3 and probably 0.9.1)
You can remove the "(void) indent;" line in TinyMqtt.h or get the latest git version.

Best regards.
