### ISSUE TITLE
Broker Never Connects

### ISSUE THREAD

**Issue by toneware** [hsaturn/TinyMqtt#35]
I used the sample broker ino file, but the broker never connects to the router. I tried several ESP8266 devices (all able to connect as mosquitto clients, FWIW), and I tried two different networks/routers. All to no avail. I'm not sure what the issue is.

**Comment by hsaturn** [comment]
Hello the git version of TinyMqtt should have fixed this.
There was a problem in ConnAck message.

**Comment by hsaturn** [comment]
Hello, I guess the problem is now fixed (dowload the latest release [there](https://github.com/hsaturn/TinyMqtt/archive/refs/tags/0.9.3.zip).
Note that a problem with installation from IDE may still exist so you have to install manually the library 0.9.3.
Let me know if that fixes your problem

**Comment by hsaturn** [comment]
Now answer and no other complain
