### ISSUE TITLE
broker without WiFi but "Ethernet.h" connection

### ISSUE THREAD

**Issue by AlesSt** [hsaturn/TinyMqtt#48]
Hi,

I am searching for ESP32 MQTT broker library (esp connected with  W5500 instead of WiFi) but havent had much luck :)

In feature list you state: Standalone (can work without WiFi) (degraded/local mode) => Degraded? meaning without any net connection?  as I couldnt make it work with Ethernet lib.

**Comment by hsaturn** [comment]
Hi

Yes, you can have in one ESP a Mqtt broker living with one or more MqttClient without wifi.
So any mqttclient can send/receive topics to/from the other client.

The broker can be connected or not to the network.
