### ISSUE TITLE
Platformio fixes

### ISSUE THREAD

**Issue by hsaturn** [hsaturn/TinyMqtt#64]
Check that examples under platformio compile and run.

The Arduino IDE compile options allows things that are not allowed under platformio. I have to refactor a little in order to make the compilation successful

**Comment by tv4you2016** [comment]
![image](https://user-images.githubusercontent.com/83761813/221161616-a107ba1c-9c16-4d99-b798-8df9421a816e.png)

**Comment by tv4you2016** [comment]
Fix: 

```
TinyString& TinyString::operator=(TinyString && other)
{
  if (this == &other) return *this;
  clear();

  //str = std::exchange(other.str, str);
  //size_ = std::exchange(other.size_, size_);
  //free_ = std::exchange(other.free_, free_);
  using std::swap;
  swap(other.str, str);
  swap(other.size_, size_);
  swap(other.free_, free_);

  return *this;
}
```

**Comment by hsaturn** [comment]
Ouch..... Thanks. Tiny string is not used yet because of this kind of bug. Thanks
