### ISSUE TITLE
TinyConsole.h: No such file or directory

### ISSUE THREAD

**Issue by lb000655712992** [hsaturn/TinyMqtt#75]
Hello,when I want deloy the library in my ESP32. I use arduino ide to compile the firmware.But the compiler return message "fatal error: TinyConsole.h: No such file or directory" for me.How can I fix the proplem?Thanks!

**Comment by real-bombinho** [comment]
You can use the library manager to install the package. If you install TinyMqtt via library manager then you normally get asked if you want to install TinyConsole as well.

**Comment by hsaturn** [comment]
Hello

TinyConsole should be installed automatically as a dependency. And real-bombinho said what can be done if not.
