### ISSUE TITLE
RP2040 support

### ISSUE THREAD

**Issue by real-bombinho** [hsaturn/TinyMqtt#78]
Add support for RP2040

suggestion has been made, comprising of adding in TinyMqtt.h:

#elif defined(ARDUINO_ARCH_RP2040)
  #include <WiFi.h>   // works with Raspberry Pi Pico W, earlephilhower

**Comment by hsaturn** [comment]
Can you write a PR for this, or a git diff ?

**Comment by hsaturn** [comment]
PR merged

**Comment by hsaturn** [comment]
Could you please tell me why you are adding #include <Ethernet.h> in W5500 examples ?
This seems not coherent with the TINY_MQTT_ETHERNET compilation flag.
