### ISSUE TITLE
Moving to GitLab

### ISSUE THREAD

**Issue by hsaturn** [hsaturn/TinyMqtt#90]
Hello

Due toi 2FA, I don't want to give my phone to ms, so I'm in the process of moving from Github to Gitlab.

The new URL is https://gitlab.com/hsaturn/TinyMqtt

Best regards

**Comment by GreenEllipsis** [comment]
You can use a TOTP app instead of providing a mobile number. I did. But moving to gitlab is cool, too.

**Comment by real-bombinho** [comment]
It is less promoted but 2FA is also possible via SMS from Github without having to have an app.

**Comment by hsaturn** [comment]
I hate this 2FA !

**Comment by real-bombinho** [comment]
I used the sms option, albeit being a pain as I am not welded to my phone, it does work not differently than other mandated 2FAs.

**Comment by hsaturn** [comment]
I hate this 2FA, but I'm done with that... I'm back to github, but without any smile on my face
